// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vplydlocixunrnjlftbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwbHlkbG9jaXh1bnJuamxmdGJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMxNTMzMjcsImV4cCI6MjA4ODcyOTMyN30.tIF8B8Ckl3lzD_9IDaBLl24RFaGpAPux1Gz2gqHZ2tc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});